In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [2]:
import sys
print(sys.executable)

/Users/rohit/venv/time-series-venv/bin/python

In [3]:
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12, 6)

In [4]:
import os
os.getcwd()

'/Users/rohit/Adaptive-Time-Series-Forecasting-Engine/src/models/classical'

In [6]:
df = pd.read_csv("../../../data/raw/sales_train_validation.csv")

In [7]:
df

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,FOODS_3_823_WI_3_validation,FOODS_3_823,FOODS_3,FOODS,WI_3,WI,0,0,2,2,...,2,0,0,0,0,0,1,0,0,1
30486,FOODS_3_824_WI_3_validation,FOODS_3_824,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30487,FOODS_3_825_WI_3_validation,FOODS_3_825,FOODS_3,FOODS,WI_3,WI,0,6,0,2,...,2,1,0,2,0,1,0,0,1,0
30488,FOODS_3_826_WI_3_validation,FOODS_3_826,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,1,0,0,1,0,3,1,3
30489,FOODS_3_827_WI_3_validation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
item_id = df.iloc[0]['id']

In [10]:
item_id

'HOBBIES_1_001_CA_1_validation'

In [11]:
sales_cols = [col for col in df.columns if col.startswith('d_')]

In [15]:
sales_cols

['d_1',
 'd_2',
 'd_3',
 'd_4',
 'd_5',
 'd_6',
 'd_7',
 'd_8',
 'd_9',
 'd_10',
 'd_11',
 'd_12',
 'd_13',
 'd_14',
 'd_15',
 'd_16',
 'd_17',
 'd_18',
 'd_19',
 'd_20',
 'd_21',
 'd_22',
 'd_23',
 'd_24',
 'd_25',
 'd_26',
 'd_27',
 'd_28',
 'd_29',
 'd_30',
 'd_31',
 'd_32',
 'd_33',
 'd_34',
 'd_35',
 'd_36',
 'd_37',
 'd_38',
 'd_39',
 'd_40',
 'd_41',
 'd_42',
 'd_43',
 'd_44',
 'd_45',
 'd_46',
 'd_47',
 'd_48',
 'd_49',
 'd_50',
 'd_51',
 'd_52',
 'd_53',
 'd_54',
 'd_55',
 'd_56',
 'd_57',
 'd_58',
 'd_59',
 'd_60',
 'd_61',
 'd_62',
 'd_63',
 'd_64',
 'd_65',
 'd_66',
 'd_67',
 'd_68',
 'd_69',
 'd_70',
 'd_71',
 'd_72',
 'd_73',
 'd_74',
 'd_75',
 'd_76',
 'd_77',
 'd_78',
 'd_79',
 'd_80',
 'd_81',
 'd_82',
 'd_83',
 'd_84',
 'd_85',
 'd_86',
 'd_87',
 'd_88',
 'd_89',
 'd_90',
 'd_91',
 'd_92',
 'd_93',
 'd_94',
 'd_95',
 'd_96',
 'd_97',
 'd_98',
 'd_99',
 'd_100',
 'd_101',
 'd_102',
 'd_103',
 'd_104',
 'd_105',
 'd_106',
 'd_107',
 'd_108',
 'd_109',
 'd_110',
 'd_111',
 'd_112',
 'd_113',
 'd_114',
 'd_115',
 'd_116',
 'd_117',
 'd_118',
 'd_119',
 'd_120',
 'd_121',
 'd_122',
 'd_123',
 'd_124',
 'd_125',
 'd_126',
 'd_127',
 'd_128',
 'd_129',
 'd_130',
 'd_131',
 'd_132',
 'd_133',
 'd_134',
 'd_135',
 'd_136',
 'd_137',
 'd_138',
 'd_139',
 'd_140',
 'd_141',
 'd_142',
 'd_143',
 'd_144',
 'd_145',
 'd_146',
 'd_147',
 'd_148',
 'd_149',
 'd_150',
 'd_151',
 'd_152',
 'd_153',
 'd_154',
 'd_155',
 'd_156',
 'd_157',
 'd_158',
 'd_159',
 'd_160',
 'd_161',
 'd_162',
 'd_163',
 'd_164',
 'd_165',
 'd_166',
 'd_167',
 'd_168',
 'd_169',
 'd_170',
 'd_171',
 'd_172',
 'd_173',
 'd_174',
 'd_175',
 'd_176',
 'd_177',
 'd_178',
 'd_179',
 'd_180',
 'd_181',
 'd_182',
 'd_183',
 'd_184',
 'd_185',
 'd_186',
 'd_187',
 'd_188',
 'd_189',
 'd_190',
 'd_191',
 'd_192',
 'd_193',
 'd_194',
 'd_195',
 'd_196',
 'd_197',
 'd_198',
 'd_199',
 'd_200',
 'd_201',
 'd_202',
 'd_203',
 'd_204',
 'd_205',
 'd_206',
 'd_207',
 'd_208',
 'd_209',
 'd_210',
 'd_211',
 'd_212',
 'd_213',
 'd_214',
 'd_215',
 'd_216',
 'd_217',
 'd_218',
 'd_219',
 'd_220',
 'd_221',
 'd_222',
 'd_223',
 'd_224',
 'd_225',
 'd_226',
 'd_227',
 'd_228',
 'd_229',
 'd_230',
 'd_231',
 'd_232',
 'd_233',
 'd_234',
 'd_235',
 'd_236',
 'd_237',
 'd_238',
 'd_239',
 'd_240',
 'd_241',
 'd_242',
 'd_243',
 'd_244',
 'd_245',
 'd_246',
 'd_247',
 'd_248',
 'd_249',
 'd_250',
 'd_251',
 'd_252',
 'd_253',
 'd_254',
 'd_255',
 'd_256',
 'd_257',
 'd_258',
 'd_259',
 'd_260',
 'd_261',
 'd_262',
 'd_263',
 'd_264',
 'd_265',
 'd_266',
 'd_267',
 'd_268',
 'd_269',
 'd_270',
 'd_271',
 'd_272',
 'd_273',
 'd_274',
 'd_275',
 'd_276',
 'd_277',
 'd_278',
 'd_279',
 'd_280',
 'd_281',
 'd_282',
 'd_283',
 'd_284',
 'd_285',
 'd_286',
 'd_287',
 'd_288',
 'd_289',
 'd_290',
 'd_291',
 'd_292',
 'd_293',
 'd_294',
 'd_295',
 'd_296',
 'd_297',
 'd_298',
 'd_299',
 'd_300',
 'd_301',
 'd_302',
 'd_303',
 'd_304',
 'd_305',
 'd_306',
 'd_307',
 'd_308',
 'd_309',
 'd_310',
 'd_311',
 'd_312',
 'd_313',
 'd_314',
 'd_315',
 'd_316',
 'd_317',
 'd_318',
 'd_319',
 'd_320',
 'd_321',
 'd_322',
 'd_323',
 'd_324',
 'd_325',
 'd_326',
 'd_327',
 'd_328',
 'd_329',
 'd_330',
 'd_331',
 'd_332',
 'd_333',
 'd_334',
 'd_335',
 'd_336',
 'd_337',
 'd_338',
 'd_339',
 'd_340',
 'd_341',
 'd_342',
 'd_343',
 'd_344',
 'd_345',
 'd_346',
 'd_347',
 'd_348',
 'd_349',
 'd_350',
 'd_351',
 'd_352',
 'd_353',
 'd_354',
 'd_355',
 'd_356',
 'd_357',
 'd_358',
 'd_359',
 'd_360',
 'd_361',
 'd_362',
 'd_363',
 'd_364',
 'd_365',
 'd_366',
 'd_367',
 'd_368',
 'd_369',
 'd_370',
 'd_371',
 'd_372',
 'd_373',
 'd_374',
 'd_375',
 'd_376',
 'd_377',
 'd_378',
 'd_379',
 'd_380',
 'd_381',
 'd_382',
 'd_383',
 'd_384',
 'd_385',
 'd_386',
 'd_387',
 'd_388',
 'd_389',
 'd_390',
 'd_391',
 'd_392',
 'd_393',
 'd_394',
 'd_395',
 'd_396',
 'd_397',
 'd_398',
 'd_399',
 'd_400',
 'd_401',
 'd_402',
 'd_403',
 'd_404',
 'd_405',
 'd_406',
 'd_407',
 'd_408',
 'd_409',
 'd_410',
 'd_411',
 'd_412',
 'd_413',
 'd_414',
 'd_415',
 'd_416',
 'd_417',
 'd_418',
 'd_419',
 'd_420',
 'd_421',
 'd_422',
 'd_423',
 'd_424',
 'd_425',
 'd_426',
 'd_427',
 'd_428',
 'd_429',
 'd_430',
 'd_431',
 'd_432',
 'd_433',
 'd_434',
 'd_435',
 'd_436',
 'd_437',
 'd_438',
 'd_439',
 'd_440',
 'd_441',
 'd_442',
 'd_443',
 'd_444',
 'd_445',
 'd_446',
 'd_447',
 'd_448',
 'd_449',
 'd_450',
 'd_451',
 'd_452',
 'd_453',
 'd_454',
 'd_455',
 'd_456',
 'd_457',
 'd_458',
 'd_459',
 'd_460',
 'd_461',
 'd_462',
 'd_463',
 'd_464',
 'd_465',
 'd_466',
 'd_467',
 'd_468',
 'd_469',
 'd_470',
 'd_471',
 'd_472',
 'd_473',
 'd_474',
 'd_475',
 'd_476',
 'd_477',
 'd_478',
 'd_479',
 'd_480',
 'd_481',
 'd_482',
 'd_483',
 'd_484',
 'd_485',
 'd_486',
 'd_487',
 'd_488',
 'd_489',
 'd_490',
 'd_491',
 'd_492',
 'd_493',
 'd_494',
 'd_495',
 'd_496',
 'd_497',
 'd_498',
 'd_499',
 'd_500',
 'd_501',
 'd_502',
 'd_503',
 'd_504',
 'd_505',
 'd_506',
 'd_507',
 'd_508',
 'd_509',
 'd_510',
 'd_511',
 'd_512',
 'd_513',
 'd_514',
 'd_515',
 'd_516',
 'd_517',
 'd_518',
 'd_519',
 'd_520',
 'd_521',
 'd_522',
 'd_523',
 'd_524',
 'd_525',
 'd_526',
 'd_527',
 'd_528',
 'd_529',
 'd_530',
 'd_531',
 'd_532',
 'd_533',
 'd_534',
 'd_535',
 'd_536',
 'd_537',
 'd_538',
 'd_539',
 'd_540',
 'd_541',
 'd_542',
 'd_543',
 'd_544',
 'd_545',
 'd_546',
 'd_547',
 'd_548',
 'd_549',
 'd_550',
 'd_551',
 'd_552',
 'd_553',
 'd_554',
 'd_555',
 'd_556',
 'd_557',
 'd_558',
 'd_559',
 'd_560',
 'd_561',
 'd_562',
 'd_563',
 'd_564',
 'd_565',
 'd_566',
 'd_567',
 'd_568',
 'd_569',
 'd_570',
 'd_571',
 'd_572',
 'd_573',
 'd_574',
 'd_575',
 'd_576',
 'd_577',
 'd_578',
 'd_579',
 'd_580',
 'd_581',
 'd_582',
 'd_583',
 'd_584',
 'd_585',
 'd_586',
 'd_587',
 'd_588',
 'd_589',
 'd_590',
 'd_591',
 'd_592',
 'd_593',
 'd_594',
 'd_595',
 'd_596',
 'd_597',
 'd_598',
 'd_599',
 'd_600',
 'd_601',
 'd_602',
 'd_603',
 'd_604',
 'd_605',
 'd_606',
 'd_607',
 'd_608',
 'd_609',
 'd_610',
 'd_611',
 'd_612',
 'd_613',
 'd_614',
 'd_615',
 'd_616',
 'd_617',
 'd_618',
 'd_619',
 'd_620',
 'd_621',
 'd_622',
 'd_623',
 'd_624',
 'd_625',
 'd_626',
 'd_627',
 'd_628',
 'd_629',
 'd_630',
 'd_631',
 'd_632',
 'd_633',
 'd_634',
 'd_635',
 'd_636',
 'd_637',
 'd_638',
 'd_639',
 'd_640',
 'd_641',
 'd_642',
 'd_643',
 'd_644',
 'd_645',
 'd_646',
 'd_647',
 'd_648',
 'd_649',
 'd_650',
 'd_651',
 'd_652',
 'd_653',
 'd_654',
 'd_655',
 'd_656',
 'd_657',
 'd_658',
 'd_659',
 'd_660',
 'd_661',
 'd_662',
 'd_663',
 'd_664',
 'd_665',
 'd_666',
 'd_667',
 'd_668',
 'd_669',
 'd_670',
 'd_671',
 'd_672',
 'd_673',
 'd_674',
 'd_675',
 'd_676',
 'd_677',
 'd_678',
 'd_679',
 'd_680',
 'd_681',
 'd_682',
 'd_683',
 'd_684',
 'd_685',
 'd_686',
 'd_687',
 'd_688',
 'd_689',
 'd_690',
 'd_691',
 'd_692',
 'd_693',
 'd_694',
 'd_695',
 'd_696',
 'd_697',
 'd_698',
 'd_699',
 'd_700',
 'd_701',
 'd_702',
 'd_703',
 'd_704',
 'd_705',
 'd_706',
 'd_707',
 'd_708',
 'd_709',
 'd_710',
 'd_711',
 'd_712',
 'd_713',
 'd_714',
 'd_715',
 'd_716',
 'd_717',
 'd_718',
 'd_719',
 'd_720',
 'd_721',
 'd_722',
 'd_723',
 'd_724',
 'd_725',
 'd_726',
 'd_727',
 'd_728',
 'd_729',
 'd_730',
 'd_731',
 'd_732',
 'd_733',
 'd_734',
 'd_735',
 'd_736',
 'd_737',
 'd_738',
 'd_739',
 'd_740',
 'd_741',
 'd_742',
 'd_743',
 'd_744',
 'd_745',
 'd_746',
 'd_747',
 'd_748',
 'd_749',
 'd_750',
 'd_751',
 'd_752',
 'd_753',
 'd_754',
 'd_755',
 'd_756',
 'd_757',
 'd_758',
 'd_759',
 'd_760',
 'd_761',
 'd_762',
 'd_763',
 'd_764',
 'd_765',
 'd_766',
 'd_767',
 'd_768',
 'd_769',
 'd_770',
 'd_771',
 'd_772',
 'd_773',
 'd_774',
 'd_775',
 'd_776',
 'd_777',
 'd_778',
 'd_779',
 'd_780',
 'd_781',
 'd_782',
 'd_783',
 'd_784',
 'd_785',
 'd_786',
 'd_787',
 'd_788',
 'd_789',
 'd_790',
 'd_791',
 'd_792',
 'd_793',
 'd_794',
 'd_795',
 'd_796',
 'd_797',
 'd_798',
 'd_799',
 'd_800',
 'd_801',
 'd_802',
 'd_803',
 'd_804',
 'd_805',
 'd_806',
 'd_807',
 'd_808',
 'd_809',
 'd_810',
 'd_811',
 'd_812',
 'd_813',
 'd_814',
 'd_815',
 'd_816',
 'd_817',
 'd_818',
 'd_819',
 'd_820',
 'd_821',
 'd_822',
 'd_823',
 'd_824',
 'd_825',
 'd_826',
 'd_827',
 'd_828',
 'd_829',
 'd_830',
 'd_831',
 'd_832',
 'd_833',
 'd_834',
 'd_835',
 'd_836',
 'd_837',
 'd_838',
 'd_839',
 'd_840',
 'd_841',
 'd_842',
 'd_843',
 'd_844',
 'd_845',
 'd_846',
 'd_847',
 'd_848',
 'd_849',
 'd_850',
 'd_851',
 'd_852',
 'd_853',
 'd_854',
 'd_855',
 'd_856',
 'd_857',
 'd_858',
 'd_859',
 'd_860',
 'd_861',
 'd_862',
 'd_863',
 'd_864',
 'd_865',
 'd_866',
 'd_867',
 'd_868',
 'd_869',
 'd_870',
 'd_871',
 'd_872',
 'd_873',
 'd_874',
 'd_875',
 'd_876',
 'd_877',
 'd_878',
 'd_879',
 'd_880',
 'd_881',
 'd_882',
 'd_883',
 'd_884',
 'd_885',
 'd_886',
 'd_887',
 'd_888',
 'd_889',
 'd_890',
 'd_891',
 'd_892',
 'd_893',
 'd_894',
 'd_895',
 'd_896',
 'd_897',
 'd_898',
 'd_899',
 'd_900',
 'd_901',
 'd_902',
 'd_903',
 'd_904',
 'd_905',
 'd_906',
 'd_907',
 'd_908',
 'd_909',
 'd_910',
 'd_911',
 'd_912',
 'd_913',
 'd_914',
 'd_915',
 'd_916',
 'd_917',
 'd_918',
 'd_919',
 'd_920',
 'd_921',
 'd_922',
 'd_923',
 'd_924',
 'd_925',
 'd_926',
 'd_927',
 'd_928',
 'd_929',
 'd_930',
 'd_931',
 'd_932',
 'd_933',
 'd_934',
 'd_935',
 'd_936',
 'd_937',
 'd_938',
 'd_939',
 'd_940',
 'd_941',
 'd_942',
 'd_943',
 'd_944',
 'd_945',
 'd_946',
 'd_947',
 'd_948',
 'd_949',
 'd_950',
 'd_951',
 'd_952',
 'd_953',
 'd_954',
 'd_955',
 'd_956',
 'd_957',
 'd_958',
 'd_959',
 'd_960',
 'd_961',
 'd_962',
 'd_963',
 'd_964',
 'd_965',
 'd_966',
 'd_967',
 'd_968',
 'd_969',
 'd_970',
 'd_971',
 'd_972',
 'd_973',
 'd_974',
 'd_975',
 'd_976',
 'd_977',
 'd_978',
 'd_979',
 'd_980',
 'd_981',
 'd_982',
 'd_983',
 'd_984',
 'd_985',
 'd_986',
 'd_987',
 'd_988',
 'd_989',
 'd_990',
 'd_991',
 'd_992',
 'd_993',
 'd_994',
 'd_995',
 'd_996',
 'd_997',
 'd_998',
 'd_999',
 'd_1000',
 ...]

In [27]:
item_sales = df[df['id'] == item_id][sales_cols].T

In [28]:
item_sales

        0
d_1     0
d_2     0
d_3     0
d_4     0
d_5     0
...    ..
d_1909  1
d_1910  3
d_1911  0
d_1912  1
d_1913  1

[1913 rows x 1 columns]

In [29]:
item_sales.columns = ['sales']

In [30]:
item_sales

        sales
d_1         0
d_2         0
d_3         0
d_4         0
d_5         0
...       ...
d_1909      1
d_1910      3
d_1911      0
d_1912      1
d_1913      1

[1913 rows x 1 columns]

In [32]:
item_sales.index = pd.date_range(start='2011-01-29', periods=len(item_sales), freq='D')

In [33]:
item_sales

            sales
2011-01-29      0
2011-01-30      0
2011-01-31      0
2011-02-01      0
2011-02-02      0
...           ...
2016-04-20      1
2016-04-21      3
2016-04-22      0
2016-04-23      1
2016-04-24      1

[1913 rows x 1 columns]

In [34]:
item_sales['sales'] = item_sales['sales'].astype(float)

In [35]:
item_sales

            sales
2011-01-29    0.0
2011-01-30    0.0
2011-01-31    0.0
2011-02-01    0.0
2011-02-02    0.0
...           ...
2016-04-20    1.0
2016-04-21    3.0
2016-04-22    0.0
2016-04-23    1.0
2016-04-24    1.0

[1913 rows x 1 columns]

In [ ]:
pr

In [39]:
plt.figure()
plt.plot(
    item_sales['Date'],
    item_sales['sales'],
    label='Daily Sales',
    color='blue',
    marker='o'
)

plt.title(f'Daily Sales for {item_id}')
plt.xlabel('Date')
plt.ylabel('Units Sold')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

KeyError: 'Date'